name: Run tests
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies and tools
        run: |
          apt update -qq
          apt install -y \
            cmake \
            g++-10 \
            libfmt-dev \
            llvm-dev \
            ninja-build
      - name: Configure CMake
        run: |
          cmake \
            -Bbuild \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_COMPILER=g++-10 \
            -GNinja
      - name: Build
        run: cmake --build build
      - name: Test
        run: cmake --build build --target tests
